version: '3.8'

services:
  django:
    container_name: django_container
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres
    volumes:
      - postgres_data:/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  postgres_data: