version: '3.8'

services:

  django:
    container_name: django_container
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres_container
    image: postgres
    volumes:
      - postgres_data:/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always
      
  mysql:
    image: mysql
    container_name: mysql_container
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/mysql/data/
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    restart: always

  adminer:
    image: adminer
    container_name: mysql_container
    restart: always
    ports:
      - 8080:8080
  
volumes:
  postgres_data:
  mysql_data: